UNRELEASED.md
packages/react-native-bpk-component-button/src/__snapshots__/BpkButton-test.android.js.snap
packages/react-native-bpk-component-button/src/utils.js
packages/react-native-bpk-component-nudger/src/__snapshots__/BpkNudger-test.android.js.snap

Tbh no idea why this was like that, but it seems to work just fine.
I temporarily added a background to the stories and it looks good:

[BPK-2009] Fix buttons on Android

---

package.json
packages/react-native-bpk-component-image/package-lock.json

Ignoring some libs we don't want greenkeeper to update

[NO-JIRA] Greenkeeper ignore libs

---

UNRELEASED.md
ios/Podfile.lock
packages/react-native-bpk-component-calendar/src/BpkCalendar.js
packages/react-native-bpk-component-calendar/src/NativeCalendar.android.js
packages/react-native-bpk-component-calendar/src/NativeCalendar.ios.js
packages/react-native-bpk-component-calendar/src/android/src/main/java/net/skyscanner/backpack/reactnative/calendar/events/CalendarChangeEvent.kt
packages/react-native-bpk-component-calendar/src/common-types.js
packages/react-native-bpk-component-calendar/stories.js

Haven't updated the Readme as that is being done in a separate PR for BPK-2221 already.

Bpk 2220 expose calendar dates utc

---

UNRELEASED.md
packages/react-native-bpk-component-icon/README.md
packages/react-native-bpk-component-icon/src/BpkIcon.js
packages/react-native-bpk-component-icon/src/__snapshots__/withRtlSupport-RTL-test.android.js.snap
packages/react-native-bpk-component-icon/src/__snapshots__/withRtlSupport-RTL-test.ios.js.snap
packages/react-native-bpk-component-icon/src/__snapshots__/withRtlSupport-test.android.js.snap
packages/react-native-bpk-component-icon/src/__snapshots__/withRtlSupport-test.ios.js.snap
packages/react-native-bpk-component-icon/src/withRtlSupport-RTL-test.android.js
packages/react-native-bpk-component-icon/src/withRtlSupport-RTL-test.ios.js
packages/react-native-bpk-component-icon/src/withRtlSupport-test.android.js
packages/react-native-bpk-component-icon/src/withRtlSupport-test.common.js
packages/react-native-bpk-component-icon/src/withRtlSupport-test.ios.js
packages/react-native-bpk-component-icon/src/withRtlSupport.js
packages/react-native-bpk-component-icon/stories.js

`withRtlSupport` will flip horizontally the icon if `I18nManager.isRTL`

Add RTL support for BpkIcon

---

package-lock.json
package.json

Closes https://github.com/Skyscanner/backpack-react-native/pull/48

Greenkeeper/danger 7.0.11

---

.github/pull_request_template.md

I'm piggybacking off of the main repo's code review guidelines to avoid duplicating it, plus the advice in there is all generic.

[No JIRA] PR template

---

.spelling
scripts/npm/create-component.js

Adds new component and package names to the `.spelling` file when the boilerplate script is used.

[NO-JIRA] Update boilerplate script

---

UNRELEASED.md
packages/react-native-bpk-component-card/package-lock.json
packages/react-native-bpk-component-card/package.json
packages/react-native-bpk-component-card/src/withDivider.js

[NO-JIRA] Update react-native-dash

---

UNRELEASED.md
android/build.gradle
ios/Podfile.lock
packages/react-native-bpk-component-calendar/src/NativeCalendar.android.js
packages/react-native-bpk-component-calendar/src/android/build.gradle
packages/react-native-bpk-component-calendar/src/android/src/main/java/net/skyscanner/backpack/reactnative/calendar/CalendarController.kt
packages/react-native-bpk-component-calendar/src/android/src/main/java/net/skyscanner/backpack/reactnative/calendar/CalendarViewManager.kt
packages/react-native-bpk-component-calendar/src/android/src/main/java/net/skyscanner/backpack/reactnative/calendar/RNCalendarView.kt

This covers the last 2 breaking changes and add support for single selection.
TODO:
Fixed here: https://github.com/Skyscanner/backpack-android/pull/215.
Will release it first and upgrade again

Bpk 2340 update bkp calendar bridge

---

UNRELEASED.md
ios/Podfile.lock
packages/react-native-bpk-component-calendar/package-lock.json
packages/react-native-bpk-component-phone-input/package-lock.json
packages/react-native-bpk-component-select/src/BpkSelect.js
packages/react-native-bpk-component-select/src/__snapshots__/BpkSelect-test.android.js.snap
packages/react-native-bpk-component-select/src/__snapshots__/BpkSelect-test.ios.js.snap
packages/react-native-bpk-component-text-input/package-lock.json

We are removing the green bottom border from selects in order to align with text inputs, see https://backpack.github.io/components/text-input?platform=native.
| Before      | After |
| ----------- | ----------- |
| ![android-before](https://user-images.githubusercontent.com/1440090/54928989-bff1af80-4f0c-11e9-9ef4-dad45096010d.png) | ![android-after](https://user-images.githubusercontent.com/1440090/54930728-af8f0400-4f0f-11e9-9098-d7c8648d179e.png) |
| ![ios-before](https://user-images.githubusercontent.com/1440090/54930758-c03f7a00-4f0f-11e9-8ca4-7ad166be5ff6.png) | ![ios-after](https://user-images.githubusercontent.com/1440090/54930757-c03f7a00-4f0f-11e9-9a24-987d9426cc41.png) | 
+ [x] Check this if you have read and followed the [contributing …

[BPK-2345]  Align `valid` selects to text input behaviour

---

packages/react-native-bpk-component-icon/package-lock.json
packages/react-native-bpk-component-icon/package.json

Greenkeeper/native/bpk svgs 6.4.2

---

UNRELEASED.md
package-lock.json
packages/react-native-bpk-component-chip/README.md
packages/react-native-bpk-component-chip/package.json
packages/react-native-bpk-component-chip/src/BpkChip-test.common.js
packages/react-native-bpk-component-chip/src/BpkChipWrapper.js
packages/react-native-bpk-component-chip/src/__snapshots__/BpkChip-test.android.js.snap
packages/react-native-bpk-component-chip/src/__snapshots__/BpkChip-test.ios.js.snap
packages/react-native-bpk-component-chip/src/common-types.js
packages/react-native-bpk-component-chip/src/theming.js
packages/react-native-bpk-component-chip/stories.js
packages/react-native-bpk-component-icon/package-lock.json
storybook/themeAttributes.js

[BPK-2381] Add theming support to BpkChip

---

UNRELEASED.md
packages/react-native-bpk-component-button/README.md
packages/react-native-bpk-component-button/src/__snapshots__/BpkButton-test.android.js.snap
packages/react-native-bpk-component-button/src/__snapshots__/BpkButton-test.ios.js.snap
packages/react-native-bpk-component-button/src/common-types.js
packages/react-native-bpk-component-button/src/styles.js
packages/react-native-bpk-component-button/src/utils.js

[BPK-2384]: Removed centerLeading and centerTrailing

---

UNRELEASED.md
packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBar.ios.js
packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBarBackButtonIOS.ios.js
packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBarIconButtonIOS.ios.js
packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBarTextButtonIOS.ios.js
packages/react-native-bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBar-iphone-x-test.ios.js.snap
packages/react-native-bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBar-test.ios.js.snap
packages/react-native-bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBarBackButtonIOS-test.ios.js.snap
packages/react-native-bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBarIconButtonIOS-test.ios.js.snap
packages/react-native-bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBarTextButtonIOS-test.ios.js.snap

[No JIRA] Increase tap area for iOS nav bar buttons

---

UNRELEASED.md
android/app/src/main/java/net/skyscanner/backpack/MainApplication.kt
android/build.gradle
packages/react-native-bpk-component-calendar/src/android/build.gradle
packages/react-native-bpk-component-calendar/src/android/src/main/java/net/skyscanner/backpack/reactnative/calendar/CalendarController.kt
packages/react-native-bpk-component-calendar/src/android/src/main/java/net/skyscanner/backpack/reactnative/calendar/CalendarViewManager.kt
packages/react-native-bpk-component-calendar/src/android/src/main/java/net/skyscanner/backpack/reactnative/calendar/RNCalendarView.kt
packages/react-native-bpk-component-calendar/src/android/src/main/java/net/skyscanner/backpack/reactnative/calendar/events/CalendarChangeEvent.kt
packages/react-native-bpk-component-calendar/stories.js

[BPK-2354] Address calendar breaking changes

---

UNRELEASED.md
package-lock.json
packages/react-native-bpk-component-star-rating/README.md
packages/react-native-bpk-component-star-rating/package-lock.json
packages/react-native-bpk-component-star-rating/package.json
packages/react-native-bpk-component-star-rating/src/BpkStar-test.common.js
packages/react-native-bpk-component-star-rating/src/BpkStar.js
packages/react-native-bpk-component-star-rating/src/BpkStarRating.js
packages/react-native-bpk-component-star-rating/src/__snapshots__/BpkStar-test.android.js.snap
packages/react-native-bpk-component-star-rating/src/__snapshots__/BpkStar-test.ios.js.snap
packages/react-native-bpk-component-star-rating/src/__snapshots__/BpkStarRating-RTL-test.js.snap
packages/react-native-bpk-component-star-rating/src/__snapshots__/BpkStarRating-test.android.js.snap
packages/react-native-bpk-component-star-rating/src/__snapshots__/BpkStarRating-test.ios.js.snap
packages/react-native-bpk-component-star-rating/src/theming.js
packages/react-native-bpk-component-star-rating/stories.js
storybook/themeAttributes.js

[BPK-2407]: Theming support for star rating

---

UNRELEASED.md
packages/react-native-bpk-component-button/README.md
packages/react-native-bpk-component-button/src/styles.js
packages/react-native-bpk-component-button/src/utils.js
packages/react-native-bpk-component-button/stories.js
storybook/themeAttributes.js

Added theming support for featured and destructive buttons

[BPK-2409]: Theming support additional buttons

---

UNRELEASED.md
android/build.gradle
packages/react-native-bpk-component-calendar/src/android/build.gradle

This will happen now if the version in the host app is not compatible.

[BPK-2403] Improve dependency resolution for the Android calendar bridge

---

UNRELEASED.md
android/build.gradle
packages/react-native-bpk-component-calendar/src/android/build.gradle

[NO-JIRA] Bump backpack-android

---

UNRELEASED.md
packages/react-native-bpk-component-button-link/src/BpkButtonLink.android.js
packages/react-native-bpk-component-button-link/src/__snapshots__/BpkButtonLink-test.android.js.snap

[BPK-2440] Fix Android button link highlight

---

UNRELEASED.md
ios/Podfile.lock
packages/react-native-bpk-component-button/README.md
packages/react-native-bpk-component-button/src/BpkButton-test.common.js
packages/react-native-bpk-component-button/src/BpkButton.android.js
packages/react-native-bpk-component-button/src/BpkButton.ios.js
packages/react-native-bpk-component-button/src/common-types.js
packages/react-native-bpk-component-button/src/theming-functions.js
packages/react-native-bpk-theming/src/types.js
storybook/themeAttributes.js

[No JIRA] Fix border radius

---

UNRELEASED.md
packages/react-native-bpk-component-chip/src/BpkChipWrapper.js
packages/react-native-bpk-component-chip/src/__snapshots__/BpkChip-test.android.js.snap
packages/react-native-bpk-component-chip/src/__snapshots__/BpkChip-test.ios.js.snap

[NO-JIRA] Fix chip selected states

---

packages/react-native-bpk-component-flat-list/src/BpkFlatListItem.android.js
packages/react-native-bpk-component-flat-list/src/BpkFlatListItemSeparator.js
packages/react-native-bpk-component-flat-list/src/BpkRadioIcon.android.js
packages/react-native-bpk-component-flat-list/src/__snapshots__/BpkFlatListItem-test.android.js.snap
packages/react-native-bpk-component-flat-list/src/__snapshots__/BpkFlatListItemSeparator-test.android.js.snap
packages/react-native-bpk-component-flat-list/src/__snapshots__/BpkFlatListItemSeparator-test.ios.js.snap
packages/react-native-bpk-component-flat-list/src/theming.js
packages/react-native-bpk-component-horizontal-nav/src/BpkHorizontalNav.js
packages/react-native-bpk-component-horizontal-nav/src/BpkHorizontalNavItem.js
packages/react-native-bpk-component-horizontal-nav/src/theming.js
packages/react-native-bpk-component-icon/package.json
packages/react-native-bpk-component-icon/src/BpkIcon.js
packages/react-native-bpk-component-icon/stories.js
packages/react-native-bpk-component-image/package.json
packages/react-native-bpk-component-image/src/BpkImage.js
packages/react-native-bpk-component-image/stories.js
packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBarBackButtonIOS.ios.js
packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBarIconButtonIOS.ios.js
packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBarTextButtonIOS.ios.js
packages/react-native-bpk-component-navigation-bar/src/TitleView.js
packages/react-native-bpk-component-phone-input/src/__snapshots__/BpkDialingCodeList-test.android.js.snap
packages/react-native-bpk-theming/index.js
packages/react-native-bpk-theming/src/types.js
packages/react-native-bpk-theming/src/util.js

[BPK-2496]: Updating gray usage in RN for components beginning with n to f

---

package-lock.json
package.json

[No JIRA] Upgrade rn storybook

---

packages/react-native-bpk-component-map/package-lock.json
packages/react-native-bpk-component-map/package.json

Greenkeeper/native/react native maps 0.24.2

---

UNRELEASED.md
packages/react-native-bpk-component-panel/src/__snapshots__/withDivider-test.android.js.snap
packages/react-native-bpk-component-panel/src/__snapshots__/withDivider-test.ios.js.snap
packages/react-native-bpk-component-panel/src/withDivider.js
packages/react-native-bpk-component-panel/stories.js

[BPK-2571]: Fix for panel padding off by default

---

CONTRIBUTING.md

[NO-JIRA] Fix CONTRIBUTING.md

---

packages/react-native-bpk-component-banner-alert/src/customPropTypes.js

[NO JIRA]: Updated banner-alert for string checking

---

package-lock.json
package.json
scripts/npm/check-owners.js

[NO-JIRA] Add progress indicator to check-owners script

---

UNRELEASED.md
packages/react-native-bpk-component-calendar/react-native-bpk-component-calendar.podspec

Increasing Backpack-iOS dependency version to support 11.0.

[NO-JIRA] increased Backpack iOS dependency version to 11.0 for Calendar

---

scripts/npm/check-owners.js

[NO-JIRA] Improve check-owners output

---

ios/Podfile.lock

[NO JIRA] Updating references for calendar and dialog

---

UNRELEASED.md
packages/react-native-bpk-theming/src/BpkThemeAttributes.js
packages/react-native-bpk-theming/stories.js

[No JIRA] Add fontFamily to BpkThemeAttributes

---

UNRELEASED.md
packages/react-native-bpk-component-phone-input/src/BpkPhoneNumberInput.js

[NO JIRA]: Fix to allow phone input field to theme correctly

---

UNRELEASED.md
packages/react-native-bpk-theming/src/types.js

[BPK-2778]: Fixed missing type for primary color

---

UNRELEASED.md
ios/Podfile
ios/Podfile.lock
package-lock.json
packages/react-native-bpk-component-calendar/react-native-bpk-component-calendar.podspec
packages/react-native-bpk-component-dialog/react-native-bpk-component-dialog.podspec

Update backpack-ios dependency

---

ios/native.xcodeproj/xcshareddata/xcschemes/Backpack Native RTL.xcscheme

Add RTL profile to iOS

---

UNRELEASED.md
ios/Podfile
ios/Podfile.lock
packages/react-native-bpk-component-calendar/react-native-bpk-component-calendar.podspec
packages/react-native-bpk-component-dialog/react-native-bpk-component-dialog.podspec
packages/react-native-bpk-component-dialog/src/ios/DialogBridge/RCTBPKDialogManager.m
packages/react-native-bpk-component-icon/package-lock.json

[BPK-2838] Update backpack-ios dependency

---

UNRELEASED.md
ios/Podfile
ios/Podfile.lock
packages/react-native-bpk-component-calendar/react-native-bpk-component-calendar.podspec
packages/react-native-bpk-component-dialog/react-native-bpk-component-dialog.podspec

Update backpack dependency

---

ios/Backpack Native-Bridging-Header.h
ios/File.swift
ios/Podfile
ios/Podfile.lock
ios/native.xcodeproj/project.pbxproj

Fix glog import error

---

package-lock.json
package.json

Update bpk dependencies

---

packages/react-native-bpk-theming/src/BpkThemeAttributes.js
packages/react-native-bpk-theming/stories.js
storybook/themeAttributes.js

[NO JIRA]: Fixing gray colors

---

UNRELEASED.md
packages/react-native-bpk-component-chip/README.md
packages/react-native-bpk-component-chip/index.js
packages/react-native-bpk-component-chip/src/BpkChip-test.common.js
packages/react-native-bpk-component-chip/src/BpkChipWrapper.js
packages/react-native-bpk-component-chip/src/BpkDismissibleChip-test.common.js
packages/react-native-bpk-component-chip/src/__snapshots__/BpkChip-test.android.js.snap
packages/react-native-bpk-component-chip/src/__snapshots__/BpkChip-test.ios.js.snap
packages/react-native-bpk-component-chip/src/__snapshots__/BpkDismissibleChip-test.android.js.snap
packages/react-native-bpk-component-chip/src/__snapshots__/BpkDismissibleChip-test.ios.js.snap
packages/react-native-bpk-component-chip/src/common-types.js
packages/react-native-bpk-component-chip/src/theming.js
packages/react-native-bpk-component-chip/stories.js
packages/react-native-bpk-theming/src/types.js
storybook/themeAttributes.js

[BPK-2868]: Chip alternate styles

---

UNRELEASED.md
packages/react-native-bpk-component-chip/src/BpkChipWrapper.js
packages/react-native-bpk-component-chip/src/__snapshots__/BpkChip-test.android.js.snap
packages/react-native-bpk-component-chip/src/__snapshots__/BpkChip-test.ios.js.snap
packages/react-native-bpk-component-chip/src/__snapshots__/BpkDismissibleChip-test.android.js.snap
packages/react-native-bpk-component-chip/src/__snapshots__/BpkDismissibleChip-test.ios.js.snap

[NO JIRA]: Updating the colors to match designs for outline chip

---

UNRELEASED.md
ios/Podfile
ios/Podfile.lock
ios/native.xcodeproj/project.pbxproj
packages/react-native-bpk-component-calendar/react-native-bpk-component-calendar.podspec
packages/react-native-bpk-component-dialog/react-native-bpk-component-dialog.podspec

Bump backpack ios dependency

---

UNRELEASED.md
packages/react-native-bpk-component-badge/README.md
packages/react-native-bpk-component-badge/package.json
packages/react-native-bpk-component-badge/src/BpkBadge-test.common.js
packages/react-native-bpk-component-badge/src/BpkBadge.js
packages/react-native-bpk-component-badge/src/__snapshots__/BpkBadge-test.android.js.snap
packages/react-native-bpk-component-badge/src/__snapshots__/BpkBadge-test.ios.js.snap
packages/react-native-bpk-component-badge/src/theming.js
packages/react-native-bpk-component-badge/stories.js
packages/react-native-bpk-theming/src/types.js
storybook/themeAttributes.js

[BPK-2877] Add destructive badge theming support

---

UNRELEASED.md
packages/react-native-bpk-component-badge/README.md
packages/react-native-bpk-component-badge/src/BpkBadge-test.common.js
packages/react-native-bpk-component-badge/src/BpkBadge.js
packages/react-native-bpk-component-badge/src/__snapshots__/BpkBadge-test.android.js.snap
packages/react-native-bpk-component-badge/src/__snapshots__/BpkBadge-test.ios.js.snap
packages/react-native-bpk-component-badge/src/theming.js
storybook/themeAttributes.js

[BPK-2877] Add more badge theming support

---

.spelling
UNRELEASED.md
packages/react-native-bpk-component-chip/README.md
packages/react-native-bpk-component-chip/src/BpkChipWrapper.js
packages/react-native-bpk-component-chip/src/BpkDismissibleChip-test.common.js
packages/react-native-bpk-component-chip/src/__snapshots__/BpkChip-test.android.js.snap
packages/react-native-bpk-component-chip/src/__snapshots__/BpkChip-test.ios.js.snap
packages/react-native-bpk-component-chip/src/__snapshots__/BpkDismissibleChip-test.android.js.snap
packages/react-native-bpk-component-chip/src/__snapshots__/BpkDismissibleChip-test.ios.js.snap
packages/react-native-bpk-component-chip/src/common-types.js

[BPK-2910] Fix chip user styling

---

.spelling
UNRELEASED.md
packages/react-native-bpk-component-phone-input/README.md
packages/react-native-bpk-component-phone-input/index.js
packages/react-native-bpk-component-phone-input/src/BpkFlag.js

[BPK-2927] Export BpkFlag

---

UNRELEASED.md
ios/Podfile.lock
packages/react-native-bpk-component-banner-alert/package.json
packages/react-native-bpk-component-banner-alert/src/BpkBannerAlert.android.js
packages/react-native-bpk-component-banner-alert/src/BpkBannerAlert.ios.js
packages/react-native-bpk-component-banner-alert/src/__snapshots__/BpkBannerAlert-test.android.js.snap
packages/react-native-bpk-component-banner-alert/src/common-types.js
packages/react-native-bpk-component-banner-alert/stories.js
packages/react-native-bpk-component-card/package.json
packages/react-native-bpk-component-card/src/withDivider.js
packages/react-native-bpk-component-card/stories.js
packages/react-native-bpk-component-carousel-indicator/package.json
packages/react-native-bpk-component-carousel-indicator/src/BpkCarouselIndicator.js
packages/react-native-bpk-component-carousel-indicator/src/BpkCarouselIndicatorDot.js
packages/react-native-bpk-component-carousel-indicator/src/__snapshots__/BpkCarouselIndicator-test.android.js.snap
packages/react-native-bpk-component-carousel-indicator/src/__snapshots__/BpkCarouselIndicator-test.ios.js.snap
packages/react-native-bpk-component-carousel-indicator/stories.js
packages/react-native-bpk-component-carousel/src/__snapshots__/BpkCarousel-test.android.js.snap
packages/react-native-bpk-component-carousel/src/__snapshots__/BpkCarousel-test.ios.js.snap

[BPK-2831]: Removed gray theming from components

---

UNRELEASED.md
packages/react-native-bpk-component-button/src/__snapshots__/BpkButton-test.android.js.snap
packages/react-native-bpk-component-button/src/__snapshots__/BpkButton-test.ios.js.snap
packages/react-native-bpk-component-flat-list/src/BpkFlatListItem.android.js
packages/react-native-bpk-component-flat-list/src/BpkFlatListItemSeparator.js
packages/react-native-bpk-component-flat-list/src/BpkRadioIcon.android.js
packages/react-native-bpk-component-flat-list/src/__snapshots__/BpkFlatListItem-test.android.js.snap
packages/react-native-bpk-component-flat-list/src/__snapshots__/BpkFlatListItem-test.ios.js.snap
packages/react-native-bpk-component-flat-list/src/__snapshots__/BpkFlatListItemSeparator-test.android.js.snap
packages/react-native-bpk-component-flat-list/src/__snapshots__/BpkFlatListItemSeparator-test.ios.js.snap
packages/react-native-bpk-component-flat-list/src/theming.js
packages/react-native-bpk-component-horizontal-nav/src/BpkHorizontalNav.js
packages/react-native-bpk-component-horizontal-nav/src/BpkHorizontalNavItem.js
packages/react-native-bpk-component-horizontal-nav/src/theming.js
packages/react-native-bpk-component-icon/package.json
packages/react-native-bpk-component-icon/src/BpkIcon.js
packages/react-native-bpk-component-icon/stories.js
packages/react-native-bpk-component-image/package.json
packages/react-native-bpk-component-image/src/BpkImage.js
packages/react-native-bpk-component-image/stories.js
packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBarBackButtonIOS.ios.js
packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBarIconButtonIOS.ios.js
packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBarTextButtonIOS.ios.js
packages/react-native-bpk-component-navigation-bar/src/TitleView.js
packages/react-native-bpk-component-phone-input/src/__snapshots__/BpkDialingCodeList-test.android.js.snap
packages/react-native-bpk-component-star-rating/src/__snapshots__/BpkStar-test.ios.js.snap
packages/react-native-bpk-component-star-rating/src/__snapshots__/BpkStarRating-RTL-test.js.snap
packages/react-native-bpk-component-star-rating/src/__snapshots__/BpkStarRating-test.android.js.snap

[BPK-2831]: Removed gray theming from components f to n

---

ios/Podfile
ios/Podfile.lock
packages/react-native-bpk-component-calendar/react-native-bpk-component-calendar.podspec
packages/react-native-bpk-component-dialog/react-native-bpk-component-dialog.podspec

[NO-JIRA] Update backpack-ios dependency

---

UNRELEASED.md
packages/react-native-bpk-component-navigation-bar/README.md
packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBar-test.android.js
packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBar.android.js
packages/react-native-bpk-component-navigation-bar/src/common-types.js
packages/react-native-bpk-theming/src/types.js
storybook/themeAttributes.js

[NO-JIRA] remove deprecated nav bar theme attribute

---

UNRELEASED.md
packages/react-native-bpk-component-icon/src/withRtlSupport.js

[NO-JIRA] Fix flow types in bpk icon

---

ios/Podfile.lock
package-lock.json
package.json

[NO-JIRA] Bump backpack dependency

---

ios/Podfile
ios/Podfile.lock
packages/react-native-bpk-component-calendar/react-native-bpk-component-calendar.podspec
packages/react-native-bpk-component-dialog/react-native-bpk-component-dialog.podspec

[NO-JIRA] Update backpack-ios-dependency

---

UNRELEASED.md
packages/react-native-bpk-component-icon/src/BpkIcon.js
packages/react-native-bpk-component-icon/src/withRtlSupport.js

[NO-JIRA] Fix flow types in BpkBadge

---

package-lock.json
package.json

[NO-JIRA] Update bpk dependencies

---

android/build.gradle

This matches the version Backpack-Android is using.
+ [x] Tests

[NO-JIRA] Update Android sdk to 29

---

UNRELEASED.md
ios/Podfile
ios/Podfile.lock
packages/react-native-bpk-component-calendar/react-native-bpk-component-calendar.podspec
packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKCalendar.h
packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKCalendar.m
packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKCalendarDateUtils.h
packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKCalendarDateUtils.m
packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKCalendarManager.m
packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTConvert+RCTBPKCalendar.h
packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTConvert+RCTBPKCalendar.m
packages/react-native-bpk-component-dialog/react-native-bpk-component-dialog.podspec
packages/react-native-bpk-component-rating/react-native-bpk-component-rating.podspec

[NO-JIRA] Upgrade backpack-ios dependency

---

ios/Podfile
ios/Podfile.lock
package-lock.json
packages/react-native-bpk-component-calendar/react-native-bpk-component-calendar.podspec
packages/react-native-bpk-component-dialog/react-native-bpk-component-dialog.podspec
packages/react-native-bpk-component-rating/react-native-bpk-component-rating.podspec

[NO-JIRA] Update backpack-ios dependency to 22

---

.spelling
packages/react-native-bpk-appearance/README.md
packages/react-native-bpk-appearance/index.js
packages/react-native-bpk-appearance/package-lock.json
packages/react-native-bpk-appearance/package.json
packages/react-native-bpk-appearance/src/BpkAppearance-test.js
packages/react-native-bpk-appearance/src/BpkAppearance.js
packages/react-native-bpk-appearance/src/BpkAppearanceProvider-test.js
packages/react-native-bpk-appearance/src/BpkAppearanceProvider.js
packages/react-native-bpk-appearance/src/BpkDynamicStyleSheet-flowtest.js
packages/react-native-bpk-appearance/src/BpkDynamicStyleSheet-test.js
packages/react-native-bpk-appearance/src/BpkDynamicStyleSheet.js
packages/react-native-bpk-appearance/src/hooks-test.js
packages/react-native-bpk-appearance/src/hooks.js
packages/react-native-bpk-appearance/stories.js
storybook/storybook.js

JS side is ready, I'll include the native bridges and stories in a follow up PR
PR to integrate it in our storybook:
- https://github.com/Skyscanner/backpack-react-native/pull/262
+ [x] Tests

[BPK-3175] Create appearance package

---

UNRELEASED.md
packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKCalendar.m

Fixes issue introduced in this PR:
https://github.com/Skyscanner/backpack-react-native/pull/258
+ [x] Tests

[NO-JIRA] Fix calendar bridge crash

---

.spelling
UNRELEASED.md
android/app/build.gradle
android/app/src/main/AndroidManifest.xml
android/app/src/main/java/net/skyscanner/backpack/MainApplication.kt
android/build.gradle
android/gradle-maven-push.gradle
android/settings.gradle
ios/Podfile
ios/Podfile.lock
package-lock.json
package.json
packages/react-native-bpk-appearance/README.md
packages/react-native-bpk-appearance/index.js
packages/react-native-bpk-appearance/package-lock.json
packages/react-native-bpk-appearance/package.json
packages/react-native-bpk-appearance/src/android/build.gradle
packages/react-native-bpk-appearance/src/android/src/main/AndroidManifest.xml
packages/react-native-bpk-appearance/stories.js
scripts/npm/native-bridges.js
storybook/storybook.js

[BPK-3175] integrate appearance package

---

ios/Podfile.lock
package-lock.json
packages/react-native-bpk-appearance/package-lock.json
packages/react-native-bpk-appearance/package.json
packages/react-native-bpk-component-calendar/package-lock.json

[NO-JIRA] Update tokens and package-lock

---

package-lock.json
packages/react-native-bpk-appearance/package-lock.json

[NO-JIRA] Fix bpk-appearance version

---

UNRELEASED.md
ios/Podfile
ios/Podfile.lock
package-lock.json
packages/react-native-bpk-appearance/package-lock.json
packages/react-native-bpk-component-calendar/react-native-bpk-component-calendar.podspec
packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKCalendar.m
packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKCalendarManager.m
packages/react-native-bpk-component-dialog/react-native-bpk-component-dialog.podspec
packages/react-native-bpk-component-rating/react-native-bpk-component-rating.podspec

[NO-JIRA] Upgrade backpack-ios

---

ios/Podfile
ios/Podfile.lock
ios/native.xcodeproj/xcshareddata/xcschemes/native.xcscheme
package-lock.json
package.json
packages/react-native-bpk-component-rating/README.md
packages/react-native-bpk-component-rating/src/BpkRating-test.common.js
packages/react-native-bpk-component-rating/src/BpkRating-test.ios.js
packages/react-native-bpk-component-rating/src/BpkRating.js
packages/react-native-bpk-component-rating/src/NativeRating.android.js
packages/react-native-bpk-component-rating/src/NativeRating.ios.js
packages/react-native-bpk-component-rating/src/__snapshots__/BpkRating-test.ios.js.snap
packages/react-native-bpk-component-rating/src/common-types.js
packages/react-native-bpk-component-rating/src/ios/RatingBridge/RCTBPKRating.h
packages/react-native-bpk-component-rating/src/ios/RatingBridge/RCTBPKRating.m
packages/react-native-bpk-component-rating/src/ios/RatingBridge/RCTBPKRatingManager.h
packages/react-native-bpk-component-rating/src/ios/RatingBridge/RCTBPKRatingManager.m
packages/react-native-bpk-component-rating/src/ios/RatingBridge/RCTBPKRatingShadowView.h
packages/react-native-bpk-component-rating/src/ios/RatingBridge/RCTBPKRatingShadowView.m
packages/react-native-bpk-component-rating/src/ios/RatingBridge/RCTConvert+RCTBPKRating.h
packages/react-native-bpk-component-rating/src/ios/RatingBridge/RCTConvert+RCTBPKRating.m
packages/react-native-bpk-component-rating/stories.js

Some decision I've made in the course of implementing this:
+ I removed the `icon` size because it's not supported on iOS.
+ I made the prop type for `StringOrArray` better by changing `Array<String>` to `[string, string, string]`. This should catch trivial errors earlier.
+ [ ] Tests
+ [ ]  Docs (either update [backpack-docs](https://github.com/Skyscanner/backpack-docs) now, or create a follow up ticket)

[BPK-2711] Rating Bridge

---

UNRELEASED.md
packages/react-native-bpk-appearance/src/BpkAppearanceProvider-test.js
packages/react-native-bpk-appearance/src/BpkAppearanceProvider.js

[BPK-3207] Add ability to override current appearance

---

UNRELEASED.md
packages/react-native-bpk-appearance/src/BpkAppearanceProvider.js

[NO-JIRA] fix improve appearance provider

---

UNRELEASED.md
packages/react-native-bpk-component-map/package-lock.json
packages/react-native-bpk-component-map/package.json

I released this as an `alpha` and tested in the app. All working as expected.
+ [x] Tests

[BPK-3170] Update react-native-maps

---

packages/react-native-bpk-component-text/package.json
packages/react-native-bpk-component-text/src/BpkText-test.common.js
packages/react-native-bpk-component-text/src/__snapshots__/BpkText-test.android.js.snap
packages/react-native-bpk-component-text/src/__snapshots__/BpkText-test.ios.js.snap
packages/react-native-bpk-component-touchable-overlay/package.json
packages/react-native-bpk-component-touchable-overlay/src/BpkTouchableOverlay-test.js
packages/react-native-bpk-component-touchable-overlay/src/__snapshots__/BpkTouchableOverlay-test.js.snap
packages/react-native-bpk-test-utils/index.js
packages/react-native-bpk-test-utils/package.json
packages/react-native-bpk-test-utils/src/describeEachColorScheme.js

[NO-JIRA] Add tests for dark mode

---

UNRELEASED.md
packages/react-native-bpk-appearance/README.md
packages/react-native-bpk-appearance/index.js
packages/react-native-bpk-appearance/src/BpkDynamicStyleSheet.js
packages/react-native-bpk-appearance/src/hooks-test.js
packages/react-native-bpk-appearance/src/hooks.js
packages/react-native-bpk-appearance/src/isDynamicValue-test.js
packages/react-native-bpk-appearance/src/isDynamicValue.js

This changes will make adding dark mode to buttons easier.
+ [x] Tests

[BPK-3239] Add useBpkDynamicStyle

---

package-lock.json
package.json
packages/react-native-bpk-appearance/README.md
scripts/npm/documentation.js

[NO-JIRA] Integrate documentation.js

---

android/build.gradle

[NO-JIRA] Update play services deps

---

ios/Podfile.lock
package-lock.json
package.json

[No JIRA] Upgrade metro-react-native-babel-preset

---

UNRELEASED.md
ios/Podfile.lock
package-lock.json
package.json
packages/react-native-bpk-component-badge/package.json
packages/react-native-bpk-component-banner-alert/package.json
packages/react-native-bpk-component-button-link/package.json
packages/react-native-bpk-component-button/package.json
packages/react-native-bpk-component-card/package.json
packages/react-native-bpk-component-chip/package.json
packages/react-native-bpk-component-flat-list/package.json
packages/react-native-bpk-component-horizontal-nav/package.json
packages/react-native-bpk-component-icon/package.json
packages/react-native-bpk-component-image/package.json
packages/react-native-bpk-component-navigation-bar/package.json
packages/react-native-bpk-component-panel/package.json
packages/react-native-bpk-component-phone-input/package.json
packages/react-native-bpk-component-progress/package.json
packages/react-native-bpk-component-section-list/package.json
packages/react-native-bpk-component-select/package.json
packages/react-native-bpk-component-spinner/package.json
packages/react-native-bpk-component-star-rating/package.json
packages/react-native-bpk-component-switch/package.json
packages/react-native-bpk-component-text-input/package.json
packages/react-native-bpk-component-text/package.json
packages/react-native-bpk-component-touchable-overlay/package.json
packages/react-native-bpk-test-utils/package.json
scripts/npm/check-bpk-dependencies.js

Tested in the app and this fixes the problems we are having with the DM flag. This also makes more sense as this has bridge code for Android and only one version can be used in the app.
+ [x] Tests

[BPK-3372] Make appearance a peer dependency

---

packages/react-native-bpk-component-banner-alert/src/BpkBannerAlert.android.js
packages/react-native-bpk-component-banner-alert/src/BpkBannerAlert.ios.js
packages/react-native-bpk-component-banner-alert/src/__snapshots__/BpkBannerAlert-test.android.js.snap
packages/react-native-bpk-component-banner-alert/src/__snapshots__/BpkBannerAlert-test.ios.js.snap

Fix message text styling for RTL

---

scripts/npm/native-bridges.js

[NO-JIRA] Improve bridge script

---

UNRELEASED.md
packages/react-native-bpk-component-banner-alert/src/BpkBannerAlert.android.js
packages/react-native-bpk-component-banner-alert/src/BpkBannerAlert.ios.js
packages/react-native-bpk-component-banner-alert/src/__snapshots__/BpkBannerAlert-test.android.js.snap
packages/react-native-bpk-component-banner-alert/src/__snapshots__/BpkBannerAlert-test.ios.js.snap

Align banner alert text writing direction for RTL correctly

---

packages/react-native-bpk-component-animate-height/stories.js

Removed the custom background so it works well in dark mode.
+ [x] Tests

[NO-JIRA] Update animated height story

---

.eslintrc
ios/Podfile.lock
package-lock.json
package.json
packages/react-native-bpk-component-image/src/BpkImage.js
packages/react-native-bpk-component-navigation-bar/src/TitleView.js
packages/react-native-bpk-component-spinner/src/BpkSpinner.js
packages/react-native-bpk-component-switch/src/BpkSwitch.js
packages/react-native-bpk-component-touchable-native-feedback/src/BpkTouchableNativeFeedback.js
packages/react-native-bpk-theming/src/util.js

My original intention was to update eslint-config-skyscanner first but that is turning out to be a bigger task than expected (https://github.com/Skyscanner/eslint-config-skyscanner/pull/31), so adding the plugin here as it is very easy to miss one of those rules.
+ [x] Tests
_If you are curious about how we review, please read through the [code review guidelines](https://github.com/Skyscanner/backpack/blob/master/CODE_REVIEW_GUIDELIN …

[NO-JIRA] Add react hooks eslint pluging and fix errors

---

UNRELEASED.md
packages/react-native-bpk-component-phone-input/README.md
packages/react-native-bpk-component-phone-input/src/BpkDialingCodeList-test.common.js
packages/react-native-bpk-component-phone-input/src/BpkDialingCodeList-test.ios.js
packages/react-native-bpk-component-phone-input/src/BpkDialingCodeList.js
packages/react-native-bpk-component-phone-input/src/__snapshots__/BpkDialingCodeList-test.android.js.snap
packages/react-native-bpk-component-phone-input/src/__snapshots__/BpkDialingCodeList-test.ios.js.snap
packages/react-native-bpk-component-phone-input/src/common-types.js

Adds the ability to have custom suggested codes at the top of the list:
+ [x] Tests

HELIOS-1191: Add a suggested into the country code selection

---

ios/Podfile
ios/Podfile.lock
packages/react-native-bpk-component-calendar/react-native-bpk-component-calendar.podspec
packages/react-native-bpk-component-dialog/react-native-bpk-component-dialog.podspec
packages/react-native-bpk-component-rating/react-native-bpk-component-rating.podspec
packages/react-native-bpk-component-text/package-lock.json

[NO-JIRA] Upgrade backpack-ios to 24.0.0

---

UNRELEASED.md
packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBar-test.android.js
packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBar-test.ios.js
packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBar.android.js
packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBar.ios.js
packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBarBackButtonIOS-test.ios.js
packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBarBackButtonIOS.ios.js
packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBarButtonAndroid-test.android.js
packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBarButtonAndroid.android.js
packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBarIconButtonIOS-test.ios.js
packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBarIconButtonIOS.ios.js
packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBarTextButtonIOS-test.ios.js
packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBarTextButtonIOS.ios.js
packages/react-native-bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBar-test.android.js.snap
packages/react-native-bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBar-test.ios.js.snap
packages/react-native-bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBarBackButtonIOS-test.ios.js.snap
packages/react-native-bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBarButtonAndroid-test.android.js.snap
packages/react-native-bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBarIconButtonIOS-test.ios.js.snap
packages/react-native-bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBarTextButtonIOS-test.ios.js.snap

[NO-JIRA] Fix navbar

---

UNRELEASED.md
packages/react-native-bpk-component-calendar/package-lock.json
packages/react-native-bpk-component-calendar/src/BpkCalendar.js
packages/react-native-bpk-component-calendar/src/NativeCalendar.android.js
packages/react-native-bpk-component-calendar/src/NativeCalendar.ios.js
packages/react-native-bpk-component-calendar/src/common-types.js

The flow types for the external Calendar component did not match the
internal native components.
+ [x] Tests

[BPK-2705] Fix flow types in calendar

---

.spelling
UNRELEASED.md
packages/react-native-bpk-component-calendar/README.md
packages/react-native-bpk-component-calendar/index.js
packages/react-native-bpk-component-calendar/src/BpkCalendar-test.common.js
packages/react-native-bpk-component-calendar/src/__snapshots__/BpkCalendar-test.android.js.snap
packages/react-native-bpk-component-calendar/src/__snapshots__/BpkCalendar-test.ios.js.snap
packages/react-native-bpk-component-calendar/src/android/src/main/java/net/skyscanner/backpack/reactnative/calendar/CalendarController.kt
packages/react-native-bpk-component-calendar/src/android/src/main/java/net/skyscanner/backpack/reactnative/calendar/CalendarViewManager.kt
packages/react-native-bpk-component-calendar/src/android/src/main/java/net/skyscanner/backpack/reactnative/calendar/DateMatcher.kt
packages/react-native-bpk-component-calendar/src/android/src/main/java/net/skyscanner/backpack/reactnative/calendar/RNCalendarView.kt
packages/react-native-bpk-component-calendar/src/android/src/main/java/net/skyscanner/backpack/reactnative/calendar/RNColorBucket.kt
packages/react-native-bpk-component-calendar/src/colorBucket-test.js
packages/react-native-bpk-component-calendar/src/colorBucket.js
packages/react-native-bpk-component-calendar/src/common-types.js
packages/react-native-bpk-component-calendar/stories.js

[BPK-3379] Add new colorBuckets prop to BpkCalendar

---

.spelling
UNRELEASED.md
packages/react-native-bpk-appearance/README.md
packages/react-native-bpk-appearance/index.js
packages/react-native-bpk-appearance/src/BpkAppearanceConsumer-test.js
packages/react-native-bpk-appearance/src/BpkAppearanceConsumer.js

[NO-JIRA] Add BpkAppearanceConsumer

---

ios/Podfile
ios/Podfile.lock
packages/react-native-bpk-component-calendar/react-native-bpk-component-calendar.podspec
packages/react-native-bpk-component-dialog/react-native-bpk-component-dialog.podspec
packages/react-native-bpk-component-rating/react-native-bpk-component-rating.podspec

[NO-JIRA] Upgrade backpack-ios to 25.0

---

scripts/npm/check-bpk-dependencies.js

Add a check to ensure `react-native-bpk-appearance` is always a peer dependency
+ [x] Tests

[NO-JIRA] Update dependency check

---

UNRELEASED.md
ios/Podfile.lock
packages/react-native-bpk-theming/README.md
packages/react-native-bpk-theming/src/BpkThemeAttributes.js

Added a warning message to be thrown for those still using this package to upgrade before we remove permenantly.

[BPK-3410]: Deprecated BpkThemeAttributes component

---

UNRELEASED.md
packages/react-native-bpk-component-animate-height/src/BpkAnimateHeight.js

[NO-JIRA] Fix flow for latest flow-bin used in the app

---

.gitignore
CONTRIBUTING.md
babel.config.js
ios/native.xcodeproj/project.pbxproj
package-lock.json
package.json
storybook/RelativeFontProvider.js
storybook/storybook.js

[BPK-3636] Enable relative for Android app

---

.env.template
package.json

[NO-JIRA] Ensure .env files is always present

---

UNRELEASED.md
ios/Podfile
ios/Podfile.lock
packages/react-native-bpk-component-calendar/react-native-bpk-component-calendar.podspec
packages/react-native-bpk-component-dialog/react-native-bpk-component-dialog.podspec
packages/react-native-bpk-component-rating/react-native-bpk-component-rating.podspec

[BPK-3381] Upgrade backpack-ios

---

.clang-format
ios/Backpack Native-Bridging-Header.h
ios/native/AppDelegate.h
ios/native/AppDelegate.m
ios/native/ToggleNavigationBarMenuModule.h
ios/native/ToggleNavigationBarMenuModule.m
ios/native/main.m
ios/nativeTests/RCTBPKCalendarDateUtilsTests.m
packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKCalendar.m
packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKCalendarDateUtils.h
packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKCalendarManager.m
packages/react-native-bpk-component-dialog/src/ios/DialogBridge/RCTBPKDialog.h
packages/react-native-bpk-component-dialog/src/ios/DialogBridge/RCTBPKDialog.m
packages/react-native-bpk-component-dialog/src/ios/DialogBridge/RCTBPKDialogButtonAction.h
packages/react-native-bpk-component-dialog/src/ios/DialogBridge/RCTBPKDialogButtonAction.m
packages/react-native-bpk-component-dialog/src/ios/DialogBridge/RCTBPKDialogEventsManager.m
packages/react-native-bpk-component-dialog/src/ios/DialogBridge/RCTBPKDialogManager.h
packages/react-native-bpk-component-dialog/src/ios/DialogBridge/RCTBPKDialogManager.m
packages/react-native-bpk-component-rating/src/ios/RatingBridge/RCTBPKRating.h
packages/react-native-bpk-component-rating/src/ios/RatingBridge/RCTBPKRating.m
packages/react-native-bpk-component-rating/src/ios/RatingBridge/RCTBPKRatingManager.h
packages/react-native-bpk-component-rating/src/ios/RatingBridge/RCTBPKRatingManager.m
packages/react-native-bpk-component-rating/src/ios/RatingBridge/RCTBPKRatingShadowView.h
packages/react-native-bpk-component-rating/src/ios/RatingBridge/RCTBPKRatingShadowView.m
packages/react-native-bpk-component-rating/src/ios/RatingBridge/RCTConvert+RCTBPKRating.h
packages/react-native-bpk-component-rating/src/ios/RatingBridge/RCTConvert+RCTBPKRating.m

[NO-JIRA] Clangify

---

UNRELEASED.md
ios/nativeTests/RCTBPKCalendarDateUtilsTests.m
packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKCalendar.h
packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKCalendar.m
packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKCalendarDateUtils.h
packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKCalendarDateUtils.m
packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKCalendarManager.m
packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKColorBucket.h
packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKColorBucket.m
packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKDateMatcher.h
packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKDateMatcher.m
packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTConvert+RCTBPKCalendar.m
packages/react-native-bpk-component-calendar/stories.js

[BPK-3381] iOS native calendar colouring bridge

---

UNRELEASED.md
android/build.gradle
ios/Podfile
ios/Podfile.lock
packages/react-native-bpk-component-calendar/index.js
packages/react-native-bpk-component-calendar/react-native-bpk-component-calendar.podspec
packages/react-native-bpk-component-calendar/src/android/build.gradle
packages/react-native-bpk-component-calendar/src/android/src/main/java/net/skyscanner/backpack/reactnative/calendar/CalendarViewManager.kt
packages/react-native-bpk-component-calendar/src/android/src/main/java/net/skyscanner/backpack/reactnative/calendar/RNCalendarView.kt
packages/react-native-bpk-component-calendar/src/android/src/main/java/net/skyscanner/backpack/reactnative/calendar/RNColorBucket.kt
packages/react-native-bpk-component-calendar/src/colorBucket-test.js
packages/react-native-bpk-component-calendar/src/colorBucket.js
packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKCalendarManager.m
packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKColorBucket.h
packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKColorBucket.m
packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTConvert+RCTBPKCalendar.m
packages/react-native-bpk-component-calendar/stories.js
packages/react-native-bpk-component-dialog/react-native-bpk-component-dialog.podspec
packages/react-native-bpk-component-dialog/src/android/build.gradle
packages/react-native-bpk-component-rating/react-native-bpk-component-rating.podspec
packages/react-native-bpk-component-rating/src/android/build.gradle

[BPK-3575] Add pre defined colour buckets to calendar

---

CONTRIBUTING.md
android/build.gradle
lib/android/build.gradle
lib/android/gradle-maven-push.gradle
scripts/release.js

Improve the android build so users using it from the source don't need to add dependencies we use only to compile the internal packages.
+ [x] Tests

[BPK-3718] adjust android build

---

package-lock.json
package.json
scripts/build.sh
scripts/npm/check-owners.js
scripts/npm/release/errors.js
scripts/npm/release/index.js
scripts/npm/release/shell.js

This removes the `release-it` lib because of a few issues we where having with it:
- It tries to pushes local branches and fails to release.
- We couldn't find a way to make it run only the npm commands in the `dist` folder and all else in root.
- We were using very little of it to be worth the trouble.
I also increased the `dryRun` coverage so now all process can be tested without publishing anything. This is more or less how the output looks:
+ [x] Tests
+ [x] Docs (either update [backpack-docs](https://github.com/Skyscanner/backpack-docs) now, or …

[BPK-3718] Improve release process

---

lib/.npmignore

[NO-JIRA] Remove mp4 from npm package

---

.spelling
UNRELEASED.md

[NO-JIRA] Fix UNRELEASED

---

lib/bpk-component-picker/src/BpkPickerMenu.android.js

Because next time this comes up I'll have forgotten why again.

[BPK-3730] Add comment about custom implementation

---

lib/ios/BackpackReactNative/Classes/CalendarBridge/RCTBPKCalendarManager.m
lib/ios/BackpackReactNative/Classes/CalendarBridge/RCTBPKDateMatcher.h
lib/ios/BackpackReactNative/Classes/CalendarBridge/RCTBPKDateMatcher.m

[BPK-3642] refactor DateMatcher helper

---

lib/android/src/androidTest/java/net/skyscanner/backpack/reactnative/rating/BpkRatingLocalDataTest.kt
lib/android/src/androidTest/java/net/skyscanner/backpack/reactnative/rating/BpkRatingShadowNodeTest.kt
lib/android/src/androidTest/java/net/skyscanner/backpack/reactnative/rating/BpkRatingViewManagerTest.kt
lib/android/src/androidTest/java/net/skyscanner/backpack/reactnative/rating/RNBpkRatingTest.kt
lib/android/src/androidTest/java/net/skyscanner/backpack/reactnative/testing/Matchers.kt
lib/android/src/main/java/net/skyscanner/backpack/reactnative/rating/BpkRatingLocalData.kt
lib/android/src/main/java/net/skyscanner/backpack/reactnative/rating/BpkRatingShadowNode.kt

[BPK-3678] Add more rating tests

---

lib/android/src/androidTest/java/net/skyscanner/backpack/reactnative/dialog/DialogViewManagerTest.kt
lib/android/src/androidTest/java/net/skyscanner/backpack/reactnative/dialog/RNDialogTest.kt
lib/android/src/androidTest/java/net/skyscanner/backpack/reactnative/dialog/events/DialogActionEventTest.kt
lib/android/src/androidTest/java/net/skyscanner/backpack/reactnative/testing/ReactViewManagerTestRule.kt
lib/android/src/main/java/net/skyscanner/backpack/reactnative/dialog/DialogViewManager.kt
lib/android/src/main/java/net/skyscanner/backpack/reactnative/dialog/RNDialog.kt

[BPK-3678] Add tests for Android dialog bridge

---

lib/android/src/androidTest/java/net/skyscanner/backpack/reactnative/calendar/CalendarControllerTest.kt
lib/android/src/androidTest/java/net/skyscanner/backpack/reactnative/calendar/CalendarViewManagerTest.kt
lib/android/src/androidTest/java/net/skyscanner/backpack/reactnative/calendar/DateMatcherTest.kt
lib/android/src/androidTest/java/net/skyscanner/backpack/reactnative/calendar/RNCalendarViewTest.kt
lib/android/src/androidTest/java/net/skyscanner/backpack/reactnative/calendar/events/CalendarChangeEventTest.kt
lib/android/src/main/java/net/skyscanner/backpack/reactnative/calendar/CalendarController.kt
lib/android/src/main/java/net/skyscanner/backpack/reactnative/calendar/CalendarViewManager.kt
lib/android/src/main/java/net/skyscanner/backpack/reactnative/calendar/DateMatcher.kt
lib/android/src/main/java/net/skyscanner/backpack/reactnative/calendar/RNCalendarView.kt

[BPK-3678] Add calendar tests

---

ios/Podfile
ios/Podfile.lock
lib/ios/BackpackReactNative/BackpackReactNative.podspec

[BPK-3763] Update backpack-ios

---

.spelling
lib/bpk-component-flare/README.md
lib/bpk-component-flare/index.js
lib/bpk-component-flare/src/BpkFlare-test.android.js
lib/bpk-component-flare/src/BpkFlare-test.common.js
lib/bpk-component-flare/src/BpkFlare-test.ios.js
lib/bpk-component-flare/src/BpkFlare.js
lib/bpk-component-flare/src/NativeFlare.android.js
lib/bpk-component-flare/src/NativeFlare.ios.js
lib/bpk-component-flare/src/__snapshots__/BpkFlare-test.android.js.snap
lib/bpk-component-flare/src/__snapshots__/BpkFlare-test.ios.js.snap
lib/bpk-component-flare/stories.js
storybook/storybook.js

Skeleton component, doesn't do anything useful yet. Because of our new monopackage, if we merge and release this it'll be available to consumers. Should we:
1. Mark it as beta in some way?
1. Don't worry, it won't be documented so people are unlikely to find it.
1. Not merge this PR until the native side is done on at least one platform?

[BPK-3762] Flare component

---

.eslintignore
jest.config.js

[NO-JIRA] Fix local dev issues

---

UNRELEASED.md
ios/Podfile.lock
lib/package.json
package-lock.json

[BPK-3763] Upgrade bpk-svgs

---

.travis.yml
package-lock.json

[NO-JIRA] Try fix CI

---

UNRELEASED.md
ios/Podfile
ios/Podfile.lock
lib/ios/BackpackReactNative/BackpackReactNative.podspec
lib/ios/BackpackReactNative/Classes/CalendarBridge/RCTBPKCalendar.h
lib/ios/BackpackReactNative/Classes/CalendarBridge/RCTBPKCalendar.m
lib/ios/BackpackReactNative/Classes/CalendarBridge/RCTBPKCalendarManager.m

+ [x] Tests - will be addressed in BPK-3679

[BPK-3642] Bridge disabled dates

---

lib/bpk-component-flare/README.md

[NO-JIRA] Fix flare docs

---

ios/NativeTests/RCTBPKRatingManagerTests.m
ios/Podfile.lock
ios/native.xcodeproj/project.pbxproj
ios/nativeTests/RCTBPKDialogManagerTests.m
lib/ios/BackpackReactNative/Classes/DialogBridge/RCTBPKDialogManager.m
lib/ios/BackpackReactNative/Classes/DialogBridge/RCTConvert+RCTBPKDialog.h
lib/ios/BackpackReactNative/Classes/DialogBridge/RCTConvert+RCTBPKDialog.m

Bpk 3758 add dialog bridge tests

---

ios/NativeTests/RCTBPKCalendarDateUtilsTests.m
ios/NativeTests/RCTBPKRatingManagerTests.m
ios/nativeTests/RCTBPKDialogManagerTests.m
lib/ios/BackpackReactNative/Classes/CalendarBridge/RCTBPKColorBucket.m
lib/ios/BackpackReactNative/Classes/CalendarBridge/RCTConvert+RCTBPKCalendar.m

[BPK-3683] Clangify

---

.github/workflows/ios-ci.yml
ios/Gemfile.lock
ios/Rakefile

[NO-JIRA] Add Github actions workflow

---

UNRELEASED.md
ios/Podfile
ios/Podfile.lock
lib/ios/BackpackReactNative/BackpackReactNative.podspec

[No JIRA] Update Backpack iOS dependency

---

android/build.gradle

This will make it easier to trigger a RN build from the Android repo and check tests pass against the latest version.
+ [x] Tests

[BPK-3684] Override backpack-android version using env

---

UNRELEASED.md
android/build.gradle
lib/android/src/main/java/net/skyscanner/backpack/reactnative/calendar/RNCalendarView.kt

[BPK-3804] Update backpack-android

---

metro.config.js

[NO-JIRA] Ignore dist folder for npm start

---

lib/bpk-component-snackbar/README.md

[NO-JIRA] Fix Snackbar readme

---

UNRELEASED.md
lib/bpk-component-text/README.md
lib/bpk-component-text/src/BpkText-test.android.js
lib/bpk-component-text/src/BpkText-test.common.js
lib/bpk-component-text/src/BpkText.js
lib/bpk-component-text/src/__snapshots__/BpkText-test.android.js.snap
lib/bpk-component-text/src/__snapshots__/BpkText-test.ios.js.snap
lib/bpk-component-text/src/common-types.js
lib/bpk-component-text/stories.js

BpkText styles inheritance support

---

UNRELEASED.md
lib/bpk-theming/src/create-with-theme.js

[No Jira] Revert changes made to `ref` behaviour on `withTheme` HOC

---

.github/workflows/ios-ci.yml
ios/native.xcodeproj/project.pbxproj

[NO-JIRA] Upgrade minimum deployment target

---

UNRELEASED.md
ios/Podfile
ios/Podfile.lock
lib/ios/BackpackReactNative/BackpackReactNative.podspec

[NO-JIRA] Upgrade backpack-ios to 34.0.0

---

package-lock.json
package.json

Now it's fully released, moving off the alpha.

[No Jira] Bump eslint-config-skyscanner to v7

---

UNRELEASED.md
ios/Podfile.lock
lib/bpk-component-banner-alert/src/AnimateAndFade.js
lib/bpk-component-banner-alert/src/__snapshots__/AnimateAndFade-test.android.js.snap
lib/bpk-component-banner-alert/src/__snapshots__/AnimateAndFade-test.ios.js.snap
lib/bpk-component-banner-alert/src/__snapshots__/BpkBannerAlert-test.android.js.snap
lib/bpk-component-banner-alert/src/__snapshots__/BpkBannerAlert-test.ios.js.snap
lib/bpk-component-banner-alert/stories.js
lib/bpk-component-horizontal-nav/src/BpkHorizontalNav.js
lib/bpk-component-horizontal-nav/src/withAnimatedProps.js

**To do**
**Done**
- horizontal nav
- banner alert
**Out of scope**
- bpk-theming uses these too, but we cannot remove them until we upgrade the theming package. There's a ticket to do this already, so we should address this as part of that ticket (soon!).

[BPK-2792] Replace UNSAFE_componentWillReceiveProps

---

UNRELEASED.md
lib/package.json
package-lock.json
package.json

[NO-JIRA] Move maps to peer dep

---

UNRELEASED.md
ios/Podfile.lock
lib/ios/BackpackReactNative/BackpackReactNative.podspec

[NO-JIRA] Add missing iOS native pod dependencies

---

UNRELEASED.md
ios/Podfile
ios/Podfile.lock
lib/ios/BackpackReactNative/BackpackReactNative.podspec

[BPK-4167] Upgrade Backpack-iOS dependency

---

.github/workflows/ios-ci.yml
ios/Rakefile

[NO-JIRA] Upgrade CI to xcode 11.7

---

UNRELEASED.md
ios/Podfile
ios/Podfile.lock
lib/ios/BackpackReactNative/BackpackReactNative.podspec
lib/ios/BackpackReactNative/Classes/CalendarBridge/RCTBPKCalendarManager.m

[BPK-3692] Prepare for breaking changes in iOS

---

UNRELEASED.md
ios/Podfile.lock
lib/bpk-component-calendar/src/NativeCalendar.ios.js
lib/ios/BackpackReactNative/BackpackReactNative.podspec
lib/ios/BackpackReactNative/Classes/CalendarBridge/RCTBPKCalendar.h
lib/ios/BackpackReactNative/Classes/CalendarBridge/RCTBPKCalendar.m
lib/ios/BackpackReactNative/Classes/CalendarBridge/RCTBPKCalendarManager.m

[BPK-4188] Apply Calendar props deterministically

---

.travis.yml

[NO-JIRA] Fail Travis redeploy if non-200-http response

---

UNRELEASED.md
ios/Podfile
ios/Podfile.lock
lib/ios/BackpackReactNative/BackpackReactNative.podspec

[BPK-4253] Update backpack-ios

---

UNRELEASED.md
ios/Podfile
ios/Podfile.lock
lib/ios/BackpackReactNative/BackpackReactNative.podspec

[NO-JIRA] Update to backpack-ios 38

---

.github/workflows/deploy-docs.yml

Adding workflow to deploy docs post android and ios CI passing

---

UNRELEASED.md
ios/Podfile
ios/Podfile.lock
lib/ios/BackpackReactNative/BackpackReactNative.podspec
lib/ios/BackpackReactNative/Classes/CalendarBridge/RCTBPKCalendarManager.m
lib/ios/BackpackReactNative/Classes/CalendarBridge/RCTBPKColorBucket.h
lib/ios/BackpackReactNative/Classes/CalendarBridge/RCTBPKColorBucket.m
lib/ios/BackpackReactNative/Classes/CalendarBridge/RCTConvert+RCTBPKCalendar.m

[BPK-4320] Adopt backpack-ios breaking changes

---

UNRELEASED.md
ios/Podfile
ios/Podfile.lock
lib/ios/BackpackReactNative/BackpackReactNative.podspec

[NO-JIRA] Upgrade Backpack-iOS to 40.0.0

---

.github/pull_request_template.md
.github/workflows/android-ci.yml
.github/workflows/deploy-docs.yml
.github/workflows/ios-ci.yml
.jirabot.yml
CHANGELOG.md
CONTRIBUTING.md
decisions/README.md
lerna.json
lib/bpk-theming/src/BpkThemeAttributes.js
scripts/npm/release/errors.js
scripts/npm/release/index.js

[BPK-4401]: Migrate to main branch

---

ios/Podfile
ios/Podfile.lock
lib/ios/BackpackReactNative/BackpackReactNative.podspec
lib/ios/BackpackReactNative/Classes/CalendarBridge/RCTBPKCalendar.h
lib/ios/BackpackReactNative/Classes/CalendarBridge/RCTBPKCalendar.m
lib/ios/BackpackReactNative/Classes/CalendarBridge/RCTBPKCalendarManager.m
lib/ios/BackpackReactNative/Classes/CalendarBridge/RCTBPKCalendarSelectionConfigurationConstants.h
lib/ios/BackpackReactNative/Classes/CalendarBridge/RCTBPKCalendarSelectionConfigurationConstants.m
lib/ios/BackpackReactNative/Classes/CalendarBridge/RCTConvert+RCTBPKCalendar.m

+ [x] Check this if you have read and followed the [contributing guidelines](https://github.com/Skyscanner/backpack-react-native/blob/main/CONTRIBUTING.md)
+ [ ] Tests

[BPK-3546] Bridge calendar breaking changes

---

UNRELEASED.md
android/build.gradle
lib/android/src/androidTest/java/net/skyscanner/backpack/reactnative/dialog/DialogViewManagerTest.kt
lib/android/src/androidTest/java/net/skyscanner/backpack/reactnative/rating/BpkRatingLocalDataTest.kt
lib/android/src/androidTest/java/net/skyscanner/backpack/reactnative/rating/BpkRatingShadowNodeTest.kt
lib/android/src/androidTest/java/net/skyscanner/backpack/reactnative/rating/BpkRatingViewManagerTest.kt
lib/android/src/androidTest/java/net/skyscanner/backpack/reactnative/rating/RNBpkRatingTest.kt
lib/android/src/main/java/net/skyscanner/backpack/reactnative/calendar/CalendarController.kt
lib/android/src/main/java/net/skyscanner/backpack/reactnative/dialog/DialogViewManager.kt
lib/android/src/main/java/net/skyscanner/backpack/reactnative/rating/BpkRatingLocalData.kt
lib/android/src/main/java/net/skyscanner/backpack/reactnative/rating/BpkRatingViewManager.kt
lib/android/src/main/java/net/skyscanner/backpack/reactnative/rating/RNBpkRating.kt

+ [ ] Check this if you have read and followed the [contributing guidelines](https://github.com/Skyscanner/backpack-react-native/blob/main/CONTRIBUTING.md)
+ [x] Tests

Updated backpack-android to v27.

---

lib/bpk-component-calendar/README.md

+ [x] Check this if you have read and followed the [contributing guidelines](https://github.com/Skyscanner/backpack-react-native/blob/main/CONTRIBUTING.md)
+ [x] Tests

[BPK-4433] Update Calendar README.md

---

lib/bpk-component-calendar/README.md

+ [x] Check this if you have read and followed the [contributing guidelines](https://github.com/Skyscanner/backpack-react-native/blob/main/CONTRIBUTING.md)
+ [x] Tests

[BPK-4433] Tiny further tweak to calendar docs

---

android/build.gradle
lib/android/gradle-maven-push.gradle

Updating the build process to publish

[KOA-4470]: Updating artifactory publish

---

UNRELEASED.md
ios/Podfile
ios/Podfile.lock
lib/ios/BackpackReactNative/BackpackReactNative.podspec

+ [x] Check this if you have read and followed the [contributing guidelines](https://github.com/Skyscanner/backpack-react-native/blob/main/CONTRIBUTING.md)
+ [x] Tests

[NO-JIRA] Update Backpack iOS dependency

---

.github/pull_request_template.md
dangerfile.js
meta.json

Added a check for outdated licensing information and improved the external contribution messaging & check
+ [ ] Tests

KOA-4571 Add outdated licensing check and update external contribution messaging

---

UNRELEASED.md
lib/android/src/androidTest/java/net/skyscanner/backpack/reactnative/calendar/CalendarViewManagerTest.kt
lib/android/src/main/java/net/skyscanner/backpack/reactnative/calendar/CalendarViewManager.kt

[NO-JIRA] Fix calendar selection

---

UNRELEASED.md
android/app/build.gradle
android/app/src/main/java/net/skyscanner/backpack/MainActivity.kt
android/app/src/main/res/values/styles.xml
android/build.gradle
lib/android/build.gradle
lib/android/gradle-maven-push.gradle
lib/android/src/androidTest/AndroidManifest.xml
lib/android/src/androidTest/java/net/skyscanner/backpack/reactnative/rating/BpkRatingLocalDataTest.kt
lib/android/src/androidTest/java/net/skyscanner/backpack/reactnative/rating/BpkRatingShadowNodeTest.kt
lib/android/src/androidTest/java/net/skyscanner/backpack/reactnative/snackbar/BpkSnackbarModuleTest.kt
lib/android/src/androidTest/java/net/skyscanner/backpack/reactnative/testing/ReactContextTestRule.kt
lib/android/src/androidTest/java/net/skyscanner/backpack/reactnative/testing/ReactViewManagerTestRule.kt
lib/android/src/main/java/net/skyscanner/backpack/reactnative/rating/BpkRatingLocalData.kt
lib/android/src/main/java/net/skyscanner/backpack/reactnative/rating/RNBpkRating.kt

Updated the project to the latest `backpack-android`. This includes changes to theming and a different publishing location. 
+ [x] Tests
+ [x] Any changes have been tested on both Android and iOS.

KOA-4715 Update backpack-android version

---

ios/Podfile
ios/Podfile.lock
lib/ios/BackpackReactNative/BackpackReactNative.podspec

+ [x] Tests
+ [x] Any changes have been tested on both Android and iOS.

[KOA-4422] Update Backpack iOS to 45.0.0

---

UNRELEASED.md
ios/Podfile
ios/Podfile.lock
lib/ios/BackpackReactNative/BackpackReactNative.podspec

updating ios to 47.1

---

CONTRIBUTING.md

Some required changes to the contributing guide after upgrading to the latest backpack-android version
+ [x] Tests
+ [x] Any changes have been tested on both Android and iOS.

Update contributing guide for Android

---

.github/workflows/ios-ci.yml
UNRELEASED.md
ios/Podfile
ios/Podfile.lock
ios/Rakefile
lib/ios/BackpackReactNative/BackpackReactNative.podspec

Updating ios to 48.0

---

UNRELEASED.md
ios/Podfile.lock
ios/native.xcodeproj/project.pbxproj

Upgrade Backpack iOS to latest to adopt colours

---

UNRELEASED.md
lib/bpk-component-chip/src/__snapshots__/BpkChip-test.android.js.snap
lib/bpk-component-chip/src/__snapshots__/BpkChip-test.ios.js.snap
lib/bpk-component-chip/src/__snapshots__/BpkDismissibleChip-test.android.js.snap
lib/bpk-component-chip/src/__snapshots__/BpkDismissibleChip-test.ios.js.snap
lib/bpk-component-select/src/__snapshots__/BpkSelect-test.android.js.snap
lib/bpk-component-select/src/__snapshots__/BpkSelect-test.ios.js.snap
lib/package.json
package-lock.json
package.json

[NO JIRA]: Bumping foundations to latest

---

lib/bpk-component-navigation-bar/src/getIOSStatusBarHeight.js

Sanpshots
| Before | After |
| ------ | ----- |
| ![before](https://user-images.githubusercontent.com/16792577/202100711-b74022d9-06c2-439f-b5e0-ccd5425f4868.png) | ![after](https://user-images.githubusercontent.com/16792577/202100777-fea84841-4f61-4e69-a01c-467291317cad.png) |
+ [ ] Tests
+ [x] Any changes have been tested on both Android and iOS.

[No Jira] Make BpkNavigationBar support iPhone 14 Pro (Max)

---

README.md
UNRELEASED.md
lib/bpk-component-phone-input/README.md
lib/bpk-theming/MIGRATION-BpkThemeAttributes.md
lib/ios/BackpackReactNative/BackpackReactNative.podspec

[KOA-5639] Remove references to backpack.github.io

---

.github/pull_request_template.md
dangerfile.js

Update pull request template
