UNRELEASED.md, packages/react-native-bpk-component-phone-input/src/__snapshots__/BpkPhoneNumberInput-test.android.js.snap, packages/react-native-bpk-component-phone-input/src/__snapshots__/BpkPhoneNumberInput-test.ios.js.snap, packages/react-native-bpk-component-text-input/src/BpkTextInput.js, packages/react-native-bpk-component-text-input/src/__snapshots__/BpkTextInput-RTL-test.js.snap, packages/react-native-bpk-component-text-input/src/__snapshots__/BpkTextInput-test.android.js.snap, packages/react-native-bpk-component-text-input/src/__snapshots__/BpkTextInput-test.ios.js.snap
I tried various things but I couldn't think of a better way 😭 
We can always revisit this in the future.
Badge, Icon, PickerMenu and TitleView (from nav bar) all do this too, so there's a precedent for it.
=> [BPK-1719] Disable font scaling on labels above accessory views

.travis.yml, ios/Podfile, ios/Podfile.lock, ios/native.xcodeproj/project.pbxproj, packages/react-native-bpk-component-calendar/README.md, packages/react-native-bpk-component-calendar/index.js, packages/react-native-bpk-component-calendar/package-lock.json, packages/react-native-bpk-component-calendar/package.json, packages/react-native-bpk-component-calendar/react-native-bpk-component-calendar.podspec, packages/react-native-bpk-component-calendar/src/BpkCalendar-test.android.js, packages/react-native-bpk-component-calendar/src/BpkCalendar-test.common.js, packages/react-native-bpk-component-calendar/src/BpkCalendar-test.ios.js, packages/react-native-bpk-component-calendar/src/BpkCalendar.android.js, packages/react-native-bpk-component-calendar/src/BpkCalendar.ios.js, packages/react-native-bpk-component-calendar/src/__snapshots__/BpkCalendar-test.android.js.snap, packages/react-native-bpk-component-calendar/src/__snapshots__/BpkCalendar-test.ios.js.snap, packages/react-native-bpk-component-calendar/src/common-types.js, packages/react-native-bpk-component-calendar/src/ios/CalendarBridge.xcodeproj/project.pbxproj, packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKCalendar.h, packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKCalendar.m, packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKCalendarManager.h, packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKCalendarManager.m, packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTConvert+RCTBPKCalendar.h, packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTConvert+RCTBPKCalendar.m, packages/react-native-bpk-component-calendar/stories.js, packages/react-native-bpk-component-map/package-lock.json, storybook/storybook.js
=> [BPK-2126] Calendar bridge

UNRELEASED.md, ios/Podfile, ios/Podfile.lock, ios/native.xcodeproj/project.pbxproj, ios/nativeTests/RCTBPKCalendarDateUtilsTests.m, packages/react-native-bpk-component-calendar/README.md, packages/react-native-bpk-component-calendar/react-native-bpk-component-calendar.podspec, packages/react-native-bpk-component-calendar/src/BpkCalendar-test.common.js, packages/react-native-bpk-component-calendar/src/NativeCalendar.android.js, packages/react-native-bpk-component-calendar/src/NativeCalendar.ios.js, packages/react-native-bpk-component-calendar/src/__snapshots__/BpkCalendar-test.ios.js.snap, packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKCalendar.h, packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKCalendar.m, packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKCalendarDateUtils.h, packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKCalendarDateUtils.m, packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKCalendarManager.m, packages/react-native-bpk-component-calendar/stories.js
Change the calendar to use UTC for the selected dates to align with
Android. Depends on merging https://github.com/Skyscanner/backpack-ios/pull/165 and then releasing `backpack-ios`.
The tests I added will not currently run on CI because we don't have CI set up to run on the macOS infrastructure of Travis. This needs to be changed, but I suggest we do another PR for it
=> [BPK-2126] Use UTC for calendar RN interface

UNRELEASED.md, ios/Podfile, ios/Podfile.lock, packages/react-native-bpk-component-calendar/react-native-bpk-component-calendar.podspec, packages/react-native-bpk-component-calendar/src/NativeCalendar.ios.js, packages/react-native-bpk-component-calendar/src/ios/CalendarBridge/RCTBPKCalendarManager.m
Fix an issue were when the calendar initialy rendered with a range
selected the component would render in a broken state.
=> [BPK-2236] Fix range render issue in calendar

UNRELEASED.md, packages/react-native-bpk-theming/README.md, packages/react-native-bpk-theming/index.js, packages/react-native-bpk-theming/src/BpkThemeAttributes-test.js, packages/react-native-bpk-theming/src/BpkThemeAttributes.js, packages/react-native-bpk-theming/src/__snapshots__/BpkThemeAttributes-test.js.snap, packages/react-native-bpk-theming/stories.js
=> [BPK-2269] Add theme attributes render prop component

packages/react-native-bpk-theming/stories.js
Fix this warning showing up in the example app:
=> [NO-JIRA] Add missing theme attribute

storybook/themeAttributes.js
The primary colour was a subtle navy blue colour before which sometimes made it hard to tell if a theme had been applied at all. With this change, we use the same 'London' theme that we use in the apps, which is easier to see.
Couple of screenshots:
=> [No JIRA] Update Storybook theme to be easier to see

android/build.gradle, packages/react-native-bpk-component-calendar/src/android/build.gradle, packages/react-native-bpk-component-calendar/src/android/src/main/java/net/skyscanner/backpack/reactnative/calendar/CalendarViewManager.kt, packages/react-native-bpk-component-calendar/src/android/src/main/java/net/skyscanner/backpack/reactnative/calendar/RNCalendarView.kt
This fixes all bugs we had with rendering the calendar, especially the year pill. An added benefit is that we've been able to remove all rn related code from `backpack-android` and all the custom layout logic lives here now. 
=> [BPK-2340] Fix calendar bridge rendering

UNRELEASED.md, packages/react-native-bpk-component-calendar/react-native-bpk-component-calendar.podspec
The pod semver range we had for Backpack previously allowed `8.0.0 <= version < 8.1.0`
Have fixed this now according to the [Cocoapod semver range docs](http://guides.cocoapods.org/using/the-podfile.html#specifying-pod-versions) to allow  `8.0.0 <= version < 9.0.0`
=> [NO-JIRA] Fix Calendar pod dependency on Backpack

UNRELEASED.md, packages/react-native-bpk-component-touchable-overlay/src/BpkTouchableOverlay-test.js, packages/react-native-bpk-component-touchable-overlay/src/BpkTouchableOverlay.js, packages/react-native-bpk-component-touchable-overlay/src/__snapshots__/BpkTouchableOverlay-test.js.snap, packages/react-native-bpk-component-touchable-overlay/stories.js
Updated the theming properties for overlay to allow border… radius numbers for when custom button radius is used.
This change allows the theming of border radius for buttons to be implemented on iOS 
=> [NO-JIRA]: Updated the theming properties for overlay

.gitignore, CONTRIBUTING.md, android/gradle-maven-push.gradle, package-lock.json, package.json, packages/react-native-bpk-component-calendar/src/android/build.gradle, scripts/npm/native-bridges.js
This PR introduces a script to publish all native bridges (only calendar for now) after a release is done. 
The script works by first recording the list of packages that are to be released, and ensuring the env is configured correctly if native bridges need to be released. This relies on `lerna changed` to find which packages are going to be released.
After the RN packages have been released the script is called again to publish the native packages based on the information saved on the first step.
_If you are curious about how we review, please read through the [code review guidelines](https://github.com/Skyscanner/backpack/blob/maste …
=> [BPK-2403] Publish native bridges automatically

UNRELEASED.md, packages/react-native-bpk-component-calendar/src/android/build.gradle
Previous version was not being recognised correctly. This version means >= 7.4 and < 8
=> [NO-JIRA] Fixed backpack android version for calendar

UNRELEASED.md, packages/react-native-bpk-component-button/src/BpkBorderedButton.ios.js, packages/react-native-bpk-component-button/src/__snapshots__/BpkButton-test.ios.js.snap, packages/react-native-bpk-component-nudger/src/__snapshots__/BpkNudger-test.ios.js.snap
Align RN iOS button border design to that on iOS Native
=> [BPK-2441] Make iOS buttons consistent

UNRELEASED.md, packages/react-native-bpk-component-calendar/src/android/build.gradle
This is not playing well with the app's build caching mechanism so we will disable it for now. Because of how we publish it (on maven) it is also not serving the original purpose so disabling it will not have any negative effect.
=> [NO-JIRA] Remove backpack-android version range

UNRELEASED.md, packages/react-native-bpk-component-calendar/react-native-bpk-component-calendar.podspec, packages/react-native-bpk-component-dialog/react-native-bpk-component-dialog.podspec
Just bumping the pod version. There's nothing that should break this in the changelog for backpack-ios
=> [BPK-2573] Update pods' Backpack ios dependency

UNRELEASED.md, ios/Podfile, ios/Podfile.lock, ios/native.xcodeproj/project.pbxproj, package-lock.json, packages/react-native-bpk-component-button/README.md, packages/react-native-bpk-component-button/src/BpkButton-test.common.js, packages/react-native-bpk-component-button/src/BpkButton.android.js, packages/react-native-bpk-component-button/src/BpkButton.ios.js, packages/react-native-bpk-component-button/src/__snapshots__/BpkButton-test.android.js.snap, packages/react-native-bpk-component-button/src/__snapshots__/BpkButton-test.ios.js.snap, packages/react-native-bpk-component-button/src/theming-functions.js
=> [BPK-2605] Icon only buttons always apply circular radius regardless of theming

android/build.gradle, packages/react-native-bpk-component-dialog/src/android/build.gradle
Update because we recently changed the signature of `addActionButton(BpkButton)` to `addActionButton(View)` and because bridges are precompiled this was still referencing the old signature and failing ci.
+ [x] Tests
=> [NO-JIRA] Update backpack-android version for dialog

UNRELEASED.md, packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBar-test.android.js, packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBar.android.js, packages/react-native-bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBar-test.android.js.snap
`navigationBarTintColor` in theme was not changing the title color in NavigationBar, only the icon. Now it changes both. Bug was only on Android, iOS was fine.
+ [x] Tests
=> Fix the title color in NavigationBar on Android

android/build.gradle
This new flag will be used to test latest versions of backpack-android against the android bridges in our ci
+ [x] Tests
=> [BPK-2685] Add flag to force backpack-android version

.spelling, UNRELEASED.md, packages/react-native-bpk-component-flat-list/README.md, packages/react-native-bpk-component-flat-list/src/BpkFlatListItem-test.common.js, packages/react-native-bpk-component-flat-list/src/BpkFlatListItem.android.js, packages/react-native-bpk-component-flat-list/src/BpkFlatListItem.ios.js, packages/react-native-bpk-component-flat-list/src/__snapshots__/BpkFlatListItem-test.android.js.snap, packages/react-native-bpk-component-flat-list/src/__snapshots__/BpkFlatListItem-test.ios.js.snap, packages/react-native-bpk-component-flat-list/src/common-types.js, packages/react-native-bpk-component-section-list/README.md
`titleProps` takes an object of properties that will be passed to the underlying BpkText instance allowing for styling of the text component.
+ [x] Tests
=> [HELIOS-1370] New Prop: 'titleProps' for react-native-bpk-component-section-list

packages/react-native-bpk-component-navigation-bar/stories.js
This PR removed the iOS hack that was previously introduced to fix a storybook issue with the UI and the header.
It seems in a newer version this issue is now fixed, therefore this PR removes the previous hack to now realign it.
Before:
After:
=> [NO JIRA]: Fixed nav stories to remove hack

UNRELEASED.md, packages/react-native-bpk-appearance/README.md, packages/react-native-bpk-appearance/src/withBpkAppearance.js, packages/react-native-bpk-component-flat-list/src/BpkFlatListItem.ios.js, packages/react-native-bpk-component-horizontal-nav/src/BpkHorizontalNav.js, packages/react-native-bpk-component-navigation-bar/src/BpkNavigationBar.ios.js
Because we use inexact types for props (so we can have ...rest) the current type definition was not able to ensure the type of a specific key after combining both types. So a prop that was initially defined as `string` would become `void | string` after using this HOC.
+ [x] Tests
=> [NO-JIRA] Fix withAppearance types

UNRELEASED.md, packages/react-native-bpk-component-picker/src/BpkPickerMenu.android.js, packages/react-native-bpk-component-picker/src/__snapshots__/BpkPicker-test.android.js.snap
The below screenshots are evidence that it matches the platform. The first screenshot is from a native Android menu and the second one is from the picker. Note how they match!
=> [BPK-3323] Changed picker scrim colour on Android

UNRELEASED.md, dangerfile.js, packages/react-native-bpk-component-text-input/README.md, packages/react-native-bpk-component-text-input/src/BpkTextInput-test.common.js, packages/react-native-bpk-component-text-input/src/BpkTextInput.js, packages/react-native-bpk-component-text-input/src/__snapshots__/BpkTextInput-RTL-test.js.snap, packages/react-native-bpk-component-text-input/src/__snapshots__/BpkTextInput-test.android.js.snap, packages/react-native-bpk-component-text-input/src/__snapshots__/BpkTextInput-test.ios.js.snap, packages/react-native-bpk-component-text-input/src/theming.js, packages/react-native-bpk-theming/src/util-test.js, packages/react-native-bpk-theming/src/util.js
**NOTE** I also fixed the danger rule that validates if an iOS `fontFamily` token is being used in Android snapshots. 
Previously it was using the wrong prop `FONT_FAMILY.VALUE` instead of `FONT_FAMILY.value`. So it was actually checking for `fontFamily` equals to `undefined`. 
+ [x] Tests
=> [BPK-3309] Fix text input font theming

UNRELEASED.md, ios/Podfile.lock, package-lock.json, packages/react-native-bpk-component-progress/README.md, packages/react-native-bpk-theming/src/util-test.js, packages/react-native-bpk-theming/src/util.js, packages/react-native-bpk-theming/stories.js
Previously, if you made no attempt to theme a component but placed it inside a `BpkThemeProvider` you would see warnings that you hadn't supplied all the required attributes.
For example:
```
<BpkThemeProvider 
theme={ /* correct theme props for button but nothing for progress bar */}
>
<BpkButton />      // Gets themed correctly
<BpkProgressBar /> // Shows warnings because you didn't pass in its theme props
</BpkThemeProvider>
```
This was fine when theming was only used for partner branding, because we never wanted non-themed components inside a `BpkThemeProvider`. However, consumers are now using theming to just theme _some_ components inside a view hierarchy.
This PR loosens the warning, so that it only fires when _some_ theme attributes _but not all_ for a component are supplied. In …
=> [BPK-3283] Fix prop type warnings for theming

UNRELEASED.md, packages/react-native-bpk-appearance/src/BpkDynamicStyleSheet-test.js, packages/react-native-bpk-appearance/src/BpkDynamicStyleSheet.js
This can happen when using `Platform.select` and providing the style for only one platform.
+ [x] Tests
=> [NO-JIRA] Guard BpkStyleSheet against undefined styles

android/build.gradle, packages/react-native-bpk-component-calendar/src/android/build.gradle
This was happening because the signature of `BpkCalendarController` changed and the bridge was compiled against an old version. Even though the change was not breaking the bitecode was no compatible anymore, and because the app uses the pre-compiled version it was breaking during runtime.
+ [x] Tests
_If you are curious about how we review, please read through the [code review …
=> [NO-JIRA] Fix calendar bridge bitecode

UNRELEASED.md, lib/bpk-component-switch/src/BpkSwitch.js, lib/bpk-component-switch/src/__snapshots__/BpkSwitch-test.android.js.snap, lib/bpk-component-switch/src/__snapshots__/BpkSwitch-test.ios.js.snap
=> [BPK-3736] Align switch DM colours to native platforms

CONTRIBUTING.md, lib/android/build.internal.gradle, lib/android/src/androidTest/java/net/skyscanner/backpack/reactnative/BpkViewStateHolderTest.kt, lib/android/src/androidTest/java/net/skyscanner/backpack/reactnative/rating/BpkRatingShadowNodeTest.kt, lib/android/src/androidTest/java/net/skyscanner/backpack/reactnative/rating/BpkRatingViewManagerTest.kt, lib/android/src/androidTest/java/net/skyscanner/backpack/reactnative/rating/RNBpkRatingTest.kt, lib/android/src/androidTest/java/net/skyscanner/backpack/reactnative/testing/ReactTestHelper.kt, lib/android/src/androidTest/java/net/skyscanner/backpack/reactnative/testing/ReactViewManagerTestRule.kt, lib/android/src/main/java/net/skyscanner/backpack/reactnative/BpkViewStateHolder.kt, lib/android/src/main/java/net/skyscanner/backpack/reactnative/rating/BpkRatingLocalData.kt, lib/android/src/main/java/net/skyscanner/backpack/reactnative/rating/BpkRatingShadowNode.kt, lib/android/src/main/java/net/skyscanner/backpack/reactnative/rating/BpkRatingViewManager.kt, lib/android/src/main/java/net/skyscanner/backpack/reactnative/rating/RNBpkRating.kt
This updates the mocking library to [mockk](https://mockk.io/) because of a few issues I had with Mockito, but especially because mockito does not support mocking final classes (classes that cannot be extended), which was forcing us to open the classes just so we could test them.
Another reason for the move is that this lib is much better for Kotlin code.
The tests now will only work with API >= 28 which is already the API used to create the `bpk-avd` emulator so no changes are needed.
I've found a bug when any of the Android views is mocked, all tests that run after the mock will fail with some weird internal error in the mocking lib (this is true for both mocking libs), so I decided to refactor the code a bit to make the logic of handling state updates and rendering the view less …
=> [BPK-3678] Update to mockk and refactor tests

UNRELEASED.md, lib/bpk-component-text-input/src/BpkTextInput-test.common.js, lib/bpk-component-text-input/src/BpkTextInput.js, lib/bpk-component-text-input/src/__snapshots__/BpkTextInput-RTL-test.js.snap, lib/bpk-component-text-input/src/__snapshots__/BpkTextInput-test.android.js.snap, lib/bpk-component-text-input/src/__snapshots__/BpkTextInput-test.ios.js.snap, lib/bpk-component-text-input/stories.js
`tinymask` sometimes formats things strangely when they contain special characters. For example:
```
const maskInstance = new tinymask('9999-9999');
// Works as expected.
maskInstance.mask('01234567') // 0123-4567
maskInstance.mask('0123-456') // 0123-456
// WTF?
maskInstance.mask('012-456') // 012 
```
This manifests in the component in the GIF you see below - when you remove a character from certain places in the string, `tinymask` reformats it and some of the characters disappear.
This PR fixes this by sanitising masked values before they're given to `tinymask`. I've also added a test for it, and made the example in our storybook make use of `useState` to make it shorter.
=> [BPK-3693] Improve mask behaviour

UNRELEASED.md, android/app/build.gradle, android/app/src/main/java/net/skyscanner/backpack/MainApplication.kt, android/build.gradle, android/gradle.properties, android/gradle/wrapper/gradle-wrapper.properties, lib/android/build.gradle, lib/android/gradle-maven-push.gradle, lib/android/src/main/java/net/skyscanner/backpack/reactnative/BackpackReactNative.kt
- Now if `USE_RELATIVE` is set to true (.env file) the native project will use the `-internal` version of backpack-android which contains relative.
- The internal build of `backpack-react-native` will now also always depend on the `-internal` version of backpack-android, this will eliminate the transitive dependency problems we been having in the app.
- Add `BackpackReactNative.init` function that will configure relative for the RN Android side when the font files are available. This will replace the custom logic we have in the app.
- It is not necessary to download and copy the relative font files for Android to use relative in the local app, as long as `USE_RELATIVE` is true and you are logged in to internal maven, relative will be used.
- While I was at it, updated gradle to latest …
=> [BPK-3680] Use internal backpack

.dependabot/config.yml, ios/Podfile.lock, package-lock.json, package.json
Upgrading Storybook stops the addons panel from working. I've made BPK-3800 to fix it, but for now let's lock the dependency.
=> [No JIRA] Revert Storybook upgrade and lock using a Dependabot config

android/build.gradle
Always adding it causes travis to try to download it from the internal repo sometimes, which fails because it's not authenticated. 
We only need it locally when building for the internal version or using relative.
+ [x] Tests
=> [BPK-3684] Add internal maven repo only when necessary

.spelling, UNRELEASED.md, ios/Podfile.lock, lib/bpk-component-horizontal-nav/README.md, lib/bpk-component-horizontal-nav/src/BpkHorizontalNav.js, lib/bpk-component-horizontal-nav/src/BpkHorizontalNavItem-test.common.js, lib/bpk-component-horizontal-nav/src/BpkHorizontalNavItem.js, lib/bpk-component-horizontal-nav/src/BpkHorizontalNavSelectedIndicator-test.common.js, lib/bpk-component-horizontal-nav/src/BpkHorizontalNavSelectedIndicator.js, lib/bpk-component-horizontal-nav/src/__snapshots__/BpkHorizontalNavItem-test.android.js.snap, lib/bpk-component-horizontal-nav/src/__snapshots__/BpkHorizontalNavItem-test.ios.js.snap, lib/bpk-component-horizontal-nav/src/__snapshots__/BpkHorizontalNavSelectedIndicator-test.android.js.snap, lib/bpk-component-horizontal-nav/src/__snapshots__/BpkHorizontalNavSelectedIndicator-test.ios.js.snap, lib/bpk-component-horizontal-nav/stories.js
Adds two new props for consumers to set styles for the text and selected indicator.
Please note that this is advanced behaviour intended to give users an 'escape hatch' for when they really need to set some custom styles to fulfil a product requirement that's not officially supported by the component yet. In this case, the product need is to use Monteverde for the colours, which this PR now enables. 
Following on from this we will begin a discussion with designers to have Monteverde an officially supported colour with proper first-party support.
=> [No Jira] Add props for custom styling horizontal nav

lib/bpk-component-dialog/stories.js
This new story uses different icon colours for light and dark mode. Note that the colour of the dialog does not change as this is only simulating dark mode in RN, not at system level, and the dialog code is native.
+ [x] Tests
=> [BPK-3818] Add dialog dynamic color example

.dependabot/config.yml, package-lock.json, package.json, storybook/storybook.js
[This issue](https://github.com/storybookjs/react-native/issues/24) is preventing us from upgrading `react-native-server` but I was able to upgrade the rest. I'm now watching that issue so can try upgrading once it's resolved.
=> [BPK-3800] Upgrade most Storybook dependencies

UNRELEASED.md, ios/Podfile.lock, lib/ios/BackpackReactNative/Classes/DialogBridge/RCTBPKDialog.m
We also need to upgrade `backpack-ios` to make this work.
+ [ ] Tests
=> Bpk 3818 enable changing dialog icon color at runtime

UNRELEASED.md, lib/bpk-component-text-input/src/BpkTextInput.js
Pretty straightforward fix. `tinymask` was only being created once, so rerenders triggered by React when props changed had no effect. This moves it to the render function and uses lodash's memoize (thanks @tiagoengel!) for efficiency.
I tested this locally in Storybook but I didn't add an example or test for it, as this is standard functionality that shouldn't regress in future (feel free to disagree, maybe I'm wrong)
=> [BPK-3842] Fix a bug where changing the 'mask' prop didn't work

CONTRIBUTING.md
The step about adding a new package to the NPM org is irrelevant now as there is only one package.
=> [NO-JIRA] Remove add-to-org step from Release

UNRELEASED.md, android/build.gradle, lib/android/build.gradle, lib/android/src/main/java/net/skyscanner/backpack/reactnative/calendar/RNFooterView.kt, lib/bpk-component-calendar/src/footerView-test.common.js, lib/bpk-component-calendar/src/footerView.js, lib/bpk-component-calendar/stories.js
=> [BPK-3855] Add descriptionOnly prop to highlightedDaysFooterView

UNRELEASED.md, lib/bpk-component-banner-alert/README.md, lib/bpk-component-banner-alert/src/BpkBannerAlert-test.common.js, lib/bpk-component-banner-alert/src/__snapshots__/BpkBannerAlert-test.android.js.snap, lib/bpk-component-banner-alert/src/__snapshots__/BpkBannerAlert-test.ios.js.snap, lib/bpk-component-banner-alert/src/common-types.js, lib/bpk-component-banner-alert/stories.js
+ [x] Tests
Turns out the iOS font “Didot” has the same emoji problem in RN
=> [BPK-4165] Allow banner-alert to accept node or string for message

lib/bpk-component-badge/stories.js
Question came up from a consumer, so I added a storybook example to save time in future. Not intended to be put on the docs site, just for our own reference.
=> [No Jira] Add edge case story for badge

UNRELEASED.md, lib/bpk-component-card/src/withDivider.js, lib/package.json, package-lock.json, package.json
Backpack RN had utilised a fork of react-native-dash due to an extraneous `new StyleSheet.create` which we changed to `StyleSheet.create`. https://github.com/obipawan/react-native-dash/compare/master...Skyscanner:master#diff-63f3aa32c5cc5d42a250b081693e9dc2R20
This has now seen to be fixed in upstream:master - https://github.com/obipawan/react-native-dash/blob/master/util.js#L20
The purpose of this PR is to migrate over to that library so that our fork can now be removed. 
As everything is still the same in the upstream library this PR just updates the package files and also the file import reference - therefore no tests have changed
=> [BPK-4190]: Migrate to upstream lib

UNRELEASED.md, lib/bpk-component-animate-height/src/BpkAnimateHeight.js, lib/bpk-component-banner-alert/src/AnimateAndFade.js, lib/bpk-component-dialog/src/NativeDialog.ios.js
Based on reading the RN source I believe this is the correct way to do refs. It doesn't result in a particularly useful type atm(`ElementRef<any>`) but at least it type checks cleanly.
+ [x] Tests
=> [No JIRA] Fix ref flow types

UNRELEASED.md, ios/Podfile.lock, lib/ios/BackpackReactNative/BackpackReactNative.podspec
This was broken in [this change](https://github.com/Skyscanner/backpack-react-native/commit/a2be01f9e8f70b4ca00090a866104a167d614246#diff-3eec611701a22e8fa36afe52da83484169b97ff2358cc5bd539d6a6147c41843R21). We should only specify the major version, not the minor or patch 👍 
+ [x] Tests
=> [BPK-4284] Fix backpack-ios dependency

README.md, UNRELEASED.md, android/app/src/main/java/net/skyscanner/backpack/MainActivity.kt, android/app/src/main/java/net/skyscanner/backpack/MainApplication.kt, android/settings.gradle, ios/Podfile.lock, ios/native.xcodeproj/project.pbxproj, ios/native/Info.plist, jest/setup.js, lib/android/build.gradle, lib/bpk-appearance/src/BpkAppearance-test.js, lib/bpk-appearance/src/BpkAppearance.js, lib/bpk-appearance/src/BpkAppearanceConsumer-test.js, lib/bpk-appearance/src/BpkAppearanceProvider-test.js, lib/bpk-appearance/src/hooks-test.js, lib/ios/BackpackReactNative/BackpackReactNative.podspec, lib/package.json, package-lock.json, package.json
The purpose of this PR is to migrate our dark mode implementation from a 3rd party library to the native solution provided by React Native >0.62.0.
The changes in this should not have an impact on consumers as the changes happen under to hood so the API remains the same.
This PR is being made to #715 on purpose as this Native support is not available in the current version of RN we are using and has come as part of the newer version upgrades that we are undertaking.
+ [x] Tests
+ [N/A] Docs (either update …
=> [BPK-4392]: Migrate dark mode

UNRELEASED.md, docs/14.0.0-calendar-accessibility-migration.md, ios/Podfile, ios/Podfile.lock, lib/bpk-component-calendar/index.js, lib/bpk-component-calendar/src/BpkCalendar-test.common.js, lib/bpk-component-calendar/src/__snapshots__/BpkCalendar-test.android.js.snap, lib/bpk-component-calendar/src/__snapshots__/BpkCalendar-test.ios.js.snap, lib/bpk-component-calendar/src/common-types-test.js, lib/bpk-component-calendar/src/common-types.js, lib/bpk-component-calendar/stories.js, lib/ios/BackpackReactNative/BackpackReactNative.podspec, lib/ios/BackpackReactNative/Classes/CalendarBridge/RCTConvert+RCTBPKCalendar.m
This PR adopts and aligns RN with the accessibility improvements on iOS. It doesn't change anything about Android. Sibling PR: https://github.com/Skyscanner/backpack-ios/pull/919
My plan is that we'll evolve the api to require consumers to call one of the `make*` functions with the appropriate arguments required by Flow etc.
Usage is would be something like 
```javascript
<BpkCalendar selectionType={makeSingleSelection(I18n.localize('CALENDAR_SINGLE_SELECTION_HINT')} {..rest}
```
I'm mostly interested in a review of this API. For a consumer the change will be switching from something like `SELECTION_TYPES.single` to the above. 
Other options:
* Make each selection type a JS class with the same flow typing. Would require a `new` which doesn't really work nicely inside the middle of a …
=> [BPK-4433] Calendar accessibility improvements(iOS)

.spelling, UNRELEASED.md, lib/bpk-component-map/README.md, lib/bpk-component-map/src/BpkIconMarker-test.common.js, lib/bpk-component-map/src/BpkIconMarker.android.js, lib/bpk-component-map/src/BpkIconMarker.ios.js, lib/bpk-component-map/src/BpkPriceMarker-test.common.js, lib/bpk-component-map/src/BpkPriceMarker.js, lib/bpk-component-map/src/__snapshots__/BpkIconMarker-test.android.js.snap, lib/bpk-component-map/src/__snapshots__/BpkIconMarker-test.ios.js.snap, lib/bpk-component-map/src/__snapshots__/BpkPriceMarker-test.android.js.snap, lib/bpk-component-map/src/__snapshots__/BpkPriceMarker-test.ios.js.snap, lib/bpk-component-map/src/icon-marker-common-types.js, lib/bpk-component-map/stories.js
Adding new `zIndex` prop to fix an issue where when a map marker was selected in a cluster of markers it would be selected behind unselected markers.
| **Price Marker Before** | **Price Marker After** |
| -- | -- |
| ![Screenshot_20210414-114256](https://user-images.githubusercontent.com/8831547/114698344-eadb1600-9d16-11eb-8fcb-1f8bc77d362e.png) | ![Screenshot_20210414-114104](https://user-images.githubusercontent.com/8831547/114698518-178f2d80-9d17-11eb-8aaa-37f30caac14a.png)
| **Icon Marker Before** | **Icon Marker After** |
| -- | -- |
| ![Screenshot_20210414-114320](https://user-images.githubusercontent.com/8831547/114698667-460d0880-9d17-11eb-8a16-971337704c9b.png) | ![Screenshot_20210414-114133](https://user-images.githubusercontent.com/8831547/114698626-38f01980-9d17-11eb-82cc-07ac …
=> [KOA-4486]: Adding new zIndex prop to map markers

.nvmrc, UNRELEASED.md, ios/Podfile.lock, lib/package.json, package.json
As Node 12 reaches EOL on 31st April 2022 - we need to upgrade the version of node we are using.
Here we have decided to just go 12 -> 14 as our current RN version supports that and is a stopgap between jumping to Node 16 as this will require a full RN version upgrade which is more involved, so to begin we have taken the simple step/solution to at least move to a minimum supported version with an idea to do an RN upgrade later this year.
+ [ ] Tests
=> [NO JIRA]: Migrate supported Node version from 12 to 14

UNRELEASED.md, ios/Podfile.lock, lib/ios/BackpackReactNative/Classes/CalendarBridge/RCTBPKCalendarDateUtils.h, lib/ios/BackpackReactNative/Classes/CalendarBridge/RCTBPKCalendarDateUtils.m, lib/ios/BackpackReactNative/Classes/CalendarBridge/RCTBPKDateMatcher.m
`RCTBPKDateMatcher` uses isBeforeDate and isAfterDate from `RCTBPKCalendarDateUtils`. 
These functions are 'non-inclusive', we have added a new 'isSameDate' function to make sure the start and end date are included when `range` is used on the iOS calendar
+ [ ] Tests
=> [KOA-4189] fix disabled highlighted dates calendar

.github/workflows/android-ci.yml
The version of the github action runner has changed, with it the version of ubuntu, and the version of the default nodejs. 
We jumped from 16 to 18, which caused problems when building RN. To fix the issue I've reset the node version with nvm during the android test stage.
+ [ ] Tests
=> Enable openssl legacy use for android builds
